# Generated by Django 3.2 on 2024-05-23 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='Цена не указана', max_length=20, verbose_name='Цена предложения'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=90, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
