# Generated by Django 3.2 on 2024-09-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20240523_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст')),
                ('price', models.CharField(default='Цена не указана', max_length=20, verbose_name='Цена предложения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Авиаилет',
                'verbose_name_plural': 'Авиабилеты',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
